services:
  - image: /images/homepage/services/services/0/image.png
    service: Specialised Coaching (Before and After School)
    content: >
      Kickstart the day or finish strong with specialist coaching sessions just
      for students! Whether it's a block of training to sharpen up their skills
      for PSSA or CHS  **Basketball, Football, Athletics (sprints, jumps,
      throws, distance)** or want to sharpen your **Fundamental Movement
      Skills**, these sessions are designed to help the students grow as an
      athlete and as a team. Our coaches will guide you to improve skills, boost
      confidence, and enjoy training in a fun and supportive environment — all
      before or after the school bell.
  - image: /images/homepage/services/services/1/image.png
    service: In-School PE & Release from Face-to-Face Teaching
    content: >
      Star-Schools offers **NESA qualified and approved** coaching that fits
      seamlessly into your school timetable. Our programs provide schools with
      high-quality **In-School PE delivery** as well as **Release from
      Face-to-Face (RFF) Teaching** options.


      We tailor each session to meet curriculum outcomes, matching sports and
      movement skills directly to the syllabus. Every lesson is structured,
      engaging, and development-focused, with **reportable outcomes** provided
      for your students.
  - image: /images/homepage/services/services/2/image.png
    service: Sporting Schools Programs
    content: >
      Star-Schools is a **registered Sporting Schools provider** for **Football,
      Basketball, and Athletics (all disciplines)**. Our qualified coaches can
      deliver complete programs across these sports, ensuring students build
      skills, confidence, and a love of movement.


      Because we are an approved provider, schools can access and apply the
      **Sporting Schools grant** to fund our programs, making high-quality
      coaching more affordable and accessible.


      With engaging sessions tailored to age and ability, Star-Schools makes it
      easy for schools to meet curriculum needs while giving every student the
      chance to shine.
  - image: /images/homepage/services/services/3/image.png
    service: School Carnivals & Special Events
    content: >
      Star-Schools takes the stress out of organising your big school events.
      From **athletics and swimming carnivals** to **gala days and special
      celebrations**, our team provides complete **planning, management, and
      execution**.


      We handle everything,  from scheduling and equipment setup to officiating,
      results, and smooth event flow, so staff can focus on supporting students.
      With our experience and professional team, schools can be confident every
      event will run seamlessly, be inclusive, and celebrate student
      achievement.
